# Generated by Django 4.2.6 on 2024-01-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_user_password_reset_token_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=255)),
                ('output_text', models.CharField(max_length=255)),
                ('match', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tests',
            field=models.ManyToManyField(blank=True, to='projects.test'),
        ),
    ]
