# Generated by Django 5.0.1 on 2024-01-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_user_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ManyToManyField(blank=True, to='projects.user'),
        ),
    ]
