# Generated by Django 5.0.1 on 2024-01-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_user_tests_user_test_alter_test_input_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.ManyToManyField(blank=True, to='projects.test'),
        ),
    ]
