# Generated by Django 4.2.6 on 2024-01-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_user_test_test_user'),
        ('projects', '0011_remove_user_tests_test_user'),
    ]

    operations = [
    ]
